### ISSUE TITLE
Training => Learn BDD

### ISSUE THREAD

**Issue by mattwynne** [cucumber-attic/website#128]
When people come to buy training from us, they're very often looking for a quick-fix commodity rather than trying to achieve the overall goal of transitioning to BDD.

I would like to try changing the way we present our training to do with more within the context of a "Learn BDD" page that explains the benefits more deeply, what needs to be done, then offers a training enquiry as a part of that.

Needs some design collaboration between Matt / Theo / Romain to figure out what this would look like,

**Comment by mattwynne** [comment]
@tooky it would be good to change the main nav text as an A/B test. I think you were going to look into some solutions for that were you?

**Comment by theo-england** [comment]
Display the overall average attendee feedback, currently 4.27/5. Perhaps as a graphic?

**Comment by tooky** [comment]
@mattwynne I've had a quick play with [splitrb](https://github.com/splitrb/split) and I don't think we can use it as is.
1. Because we are using Jekyll, even dynamically, we can't use the `ab_test` method inside our pages. We can probably add it to the view_context, but we need to include quite a lot of the sinatra helpers, e.g. sessions in there too... and anyway...
2. I think we use proxy caching in front of the website to make it fast, don't we? So we probably need to use javascript to change the pages.

I think it should still be possible to use splitrb to give us a backend for picking alternatives.

**Comment by tooky** [comment]
It might be better to look at something like this though: https://github.com/danmaz74/ABalytics and just use Google Analytics for tracking.

**Comment by mattwynne** [comment]
@tooky FYI we don't use Jekyll anymore, but you're right it's not a plain-old sinatra app either.

I think we might be able to make it work though. @romaingweb would you like to do a bit of investigation?

**Comment by mattwynne** [comment]
Closing due to age.
